# SPDX-FileCopyrightText: 2022 - 2025 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

FROM meddream/token-service:2.1.6

# optional env var
# MEDDREAM_TOKEN_USER
# MEDDREAM_TOKEN_PWD


COPY token-service.application.properties /opt/token/application.properties