# SPDX-FileCopyrightText: 2022 - 2025 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

FROM python:3.11

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /
RUN pip install -r requirements.txt

RUN mkdir /orthanc_auth_service
COPY orthanc_auth_service /orthanc_auth_service

WORKDIR /orthanc_auth_service
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port" , "8000"]

