# SPDX-FileCopyrightText: 2022 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

FROM python:3.10

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /
RUN pip install -r requirements.txt

RUN mkdir /orthanc_anonymizer
COPY orthanc_anonymizer /orthanc_anonymizer

WORKDIR /orthanc_anonymizer
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port" , "8000"]

