# SPDX-FileCopyrightText: 2022 - 2025 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

FROM jonasal/nginx-certbot:6.0.0

RUN mkdir /etc/nginx/enabled-reverse-proxies
RUN mkdir /scripts-ot
ADD nginx/nginx-common.conf /etc/nginx/includes/

ADD nginx/reverse-proxy.* /etc/nginx/disabled-reverse-proxies/

ADD nginx/orthanc-nginx-certbot.conf /etc/nginx/user_conf.d/

COPY nginx/docker-entrypoint-certbot.sh /scripts-ot/
COPY nginx/copy-conf-files.sh /scripts-ot/

RUN ls -al /etc/nginx/disabled-reverse-proxies/

ENTRYPOINT ["./scripts-ot/docker-entrypoint-certbot.sh"]

